name: Genarate Functions
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORTATS_FUNC: ${{ format('{0},{1}','Hi','World') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url,',') }}